### ISSUE TITLE
Searchfield: Add cancel button

### ISSUE THREAD

**Issue by thulium3** [lemaiwo/SAPWebIDELibraryManager#3]
Currently when searching and there is no result the progress bar is moving forever.
Add a cancel button or cancel search automatically when the feature is hidden via toolbar button

**Comment by lemaiwo** [comment]
I've added a cancel button to cancel the ongoing search request. Also implemented that it will cancel the previous search request when searching again. For that reason I've labeled it as a bug. Should be fixed now.

Thanks for reporting!
