### ISSUE TITLE
Files of assets with more then 100 entries are not displayed

### ISSUE THREAD

**Issue by gembeconsulting** [lemaiwo/SAPWebIDELibraryManager#6]
Due to an error with Model.iSizeLimit not all files are displayed. However, the no-shows are considered as to-be downloaded and to-be injected into manifest file. This results into a) missing files in the download list and b) unwanted files in your project.
You can reproduce this behavior when searching for "moment.js".
 
I already provided a casual fix with Pull Request #5

**Comment by lemaiwo** [comment]
Thanks for reporting this error. I still had some issues so I've replaced your fix to the place where I fetch all the data and set a total of all lines. 

It's deployed, Could you try again?
