### ISSUE TITLE
LibraryManager not reachable

### ISSUE THREAD

**Issue by gembeconsulting** [lemaiwo/SAPWebIDELibraryManager#7]
Dear @lemaiwo 
I've tried to include the LibraryManager into my SAP Web IDE Full-Stack instance.
After creating the required destination within Cloud Platform Cockpit, when I try to check the destination, I receive an 404 error:
Connection to "LibraryManager" established. Response returned: "404: Not Found"

![image](https://user-images.githubusercontent.com/23417978/40111796-3a839bdc-5904-11e8-937c-ed64abbee775.png)

Is the URL (...)sapwebidelibrarymanager-a6ac3f497(...) still correct?

Kind Regards,
Philipp

**Comment by lemaiwo** [comment]
Hi Philipp,

In the full stack version, this feature is by default in the Web IDE. No need to create a destination.

Kind regards,
Wouter
